### ISSUE TITLE
If players say the first letter in their username, chat formatting breaks.

### ISSUE THREAD

**Issue by inklit** [hsyyid/EssentialCmds#111]
```
[04:55:58] [Server thread/ERROR] [Sponge]: Could not pass ServerChatEvent to org.spongepowered.mod.plugin.SpongeModPluginContainer@6f858edf
java.lang.StringIndexOutOfBoundsException: String index out of range: -13
        at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:908) ~[?:1.8.0_45-internal]
        at java.lang.StringBuilder.substring(StringBuilder.java:76) ~[?:1.8.0_45-internal]
        at io.github.hsyyid.essentialcmds.listeners.MessageSinkListener.onMessage(MessageSinkListener.java:197) ~[MessageSinkListener.class:?]
        at org.spongepowered.common.event.listener.ChatListener_MessageSinkListener_onMessage41.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1509]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:210) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1509]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:157) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1509]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:89) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:78) [EventBus.class:?]
        at net.minecraft.network.NetHandlerPlayServer.handler$injectChatEvent$0(NetHandlerPlayServer.java:78) [lm.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:799) [lm.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:119) [PacketUtil.class:1.8.9-1890-4.2.0-BETA-1509]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fh$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

```

**Comment by inklit** [comment]
Actually it isn't just the first letter of their username.
If they say their entire username or any part of it like this:
BTC: B
BTC: BT
BTC: BTC
all of those messages would have broken chat formatting.
