### ISSUE TITLE
Mail.json error

### ISSUE THREAD

**Issue by seema84** [hsyyid/EssentialCmds#115]
Sponge Vanilla 1.10.2-5.0.0-BETA-91
EssentialCmds EssentialCmds-1.10.2-8.1.12

```
[08:34:42 ERROR] [essentialcmds]: Error while reading Mail:
[08:34:42 ERROR] [STDERR]: java.nio.file.NoSuchFileException: Mail.json
[08:34:42 ERROR] [STDERR]:      at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
[08:34:42 ERROR] [STDERR]:      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[08:34:42 ERROR] [STDERR]:      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[08:34:42 ERROR] [STDERR]:      at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
[08:34:42 ERROR] [STDERR]:      at java.nio.file.Files.newByteChannel(Unknown Source)
[08:34:42 ERROR] [STDERR]:      at java.nio.file.Files.newByteChannel(Unknown Source)
[08:34:42 ERROR] [STDERR]:      at java.nio.file.Files.readAllBytes(Unknown Source)
[08:34:42 ERROR] [STDERR]:      at io.github.hsyyid.essentialcmds.utils.Utils.readFile(Utils.java:809)
[08:34:42 ERROR] [STDERR]:      at io.github.hsyyid.essentialcmds.utils.Utils.readMail(Utils.java:793)
[08:34:42 ERROR] [STDERR]:      at io.github.hsyyid.essentialcmds.EssentialCmds.onServerInit(EssentialCmds.jav
a:200)
[08:34:42 ERROR] [STDERR]:      at org.spongepowered.common.event.listener.GameInitializationEventListener_Ess
entialCmds_onServerInit3.handle(Unknown Source)
[08:34:42 ERROR] [STDERR]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener
.java:95)
[08:34:42 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.j
ava:261)
[08:34:42 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.j
ava:274)
[08:34:42 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.j
ava:278)
[08:34:42 ERROR] [STDERR]:      at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:194)
[08:34:42 ERROR] [STDERR]:      at org.spongepowered.server.SpongeVanilla.initialize(SpongeVanilla.java:199)
[08:34:42 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.handler$onServerInitialize$0
(SourceFile:70)
[08:34:42 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:185)

[08:34:42 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.run(SourceFile:428)
[08:34:42 ERROR] [STDERR]:      at java.lang.Thread.run(Unknown Source)
```

**Comment by hsyyid** [comment]
This happens on first launch but then should no longer happen. I will fix this so it does not happen at all.
