### ISSUE TITLE
Error while reading Mail

### ISSUE THREAD

**Issue by matty45** [hsyyid/EssentialCmds#132]
```
[14:14:27] [Server thread/ERROR] [io.github.hsyyid.essentialcmds]: Error while reading Mail:
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]: java.nio.file.NoSuchFileException: Mail.json
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at java.nio.file.Files.newByteChannel(Unknown Source)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at java.nio.file.Files.newByteChannel(Unknown Source)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at java.nio.file.Files.readAllBytes(Unknown Source)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at io.github.hsyyid.essentialcmds.utils.Utils.readFile(Utils.java:809)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at io.github.hsyyid.essentialcmds.utils.Utils.readMail(Utils.java:793)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at io.github.hsyyid.essentialcmds.EssentialCmds.onServerInit(EssentialCmds.java:200)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at org.spongepowered.common.event.listener.GameInitializationEventListener_EssentialCmds_onServerInit3.handle(Unknown Source)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:349)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:390)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:205)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at java.lang.reflect.Method.invoke(Unknown Source)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at java.lang.reflect.Method.invoke(Unknown Source)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:788)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
[14:14:27] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.Utils:readMail:798]:    at java.lang.Thread.run(Unknown Source)
```

**Comment by MarkTwoFive** [comment]
Related or duplicate to #115 
Also, please use hastebin.com/pastebin.com for logs.
~~The current format is hardly readable.~~
