### ISSUE TITLE
[1.9.4]sethome failed

### ISSUE THREAD

**Issue by ghost** [hsyyid/EssentialCmds#143]
when i use the plugins in my  server and run the command "/sethome aaa" ,then nothing happens,so i checked the log and find this:
`[15:31:35] [pool-2-thread-6/ERROR] [Sponge/sponge]: The Scheduler tried to run the task io.github.hsyyid.essentialcmds-A-9 owned by org.spongepowered.mod.plugin.SpongeModPluginContainer@69ea2ab7, but an error occured.
java.lang.NoSuchMethodError: org.spongepowered.api.service.permission.Subject.getOption(Ljava/lang/String;)Ljava/util/Optional;
    at io.github.hsyyid.essentialcmds.cmdexecutors.SetHomeExecutor.executeAsync(SetHomeExecutor.java:52) ~[SetHomeExecutor.class:?]
    at io.github.hsyyid.essentialcmds.internal.AsyncCommandExecutorBase.lambda$execute$0(AsyncCommandExecutorBase.java:54) ~[AsyncCommandExecutorBase.class:?]
    at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.9.4-1968-5.0.0-BETA-1503]
    at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.9.4-1968-5.0.0-BETA-1503]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_102]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]`

then, i checked the source,and find that the lasted version you released on 1.9.4 is based on "spongeforge-1.9.4-1968-5.0.0-BETA-1503" and there is no method which is names as getOption() in  "org.spongepowered.api.service.permission.Subject" ,so please fixed it(you plugin version is "EssentialCmds-1.9.4-8.1.12)

**Comment by kinggoesgaming** [comment]
Sponge is not available for 1.9.4 use 1.10.2 or 1.8.9 versions...
