### ISSUE TITLE
[1.10.2] [spongeforge-1.10.2-2092-5.0.0-BETA-1750] Error while loading

### ISSUE THREAD

**Issue by mister-man** [hsyyid/EssentialCmds#146]
Hello together,

I found these bug while loading with the newes sponge and forge version:

```
[14:44:45] [Server thread/ERROR] [Sponge]: Could not pass GameStoppingEvent$Impl to Plugin{id=io.github.hsyyid.essentialcmds, name=EssentialCmds, version=@project.informativeVersion@, description=This plugin features many commands and useful features for server admins., source=/srv/server/minecraft/mods/EssentialCmds-1.10.2-8.1.14-universal.jar}
java.lang.ExceptionInInitializerError
        at io.github.hsyyid.essentialcmds.utils.Utils.<clinit>(Utils.java:102) ~[Utils.class:?]
        at io.github.hsyyid.essentialcmds.EssentialCmds.onServerStopping(EssentialCmds.java:234) ~[EssentialCmds.class:?]
        at org.spongepowered.common.event.listener.GameStoppingEventListener_EssentialCmds_onServerStopping5.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2092-5.0.0-BETA-1750]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:353) [SpongeModEventManager.class:1.10.2-2092-5.0.0-BETA-1750]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:394) [SpongeModEventManager.class:1.10.2-2092-5.0.0-BETA-1750]
        at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:197) [SpongeImpl.class:1.10.2-2092-5.0.0-BETA-1750]
        at org.spongepowered.common.SpongeImpl.postShutdownEvents(SpongeImpl.java:201) [SpongeImpl.class:1.10.2-2092-5.0.0-BETA-1750]
        at net.minecraft.server.dedicated.DedicatedServer.handler$postGameStoppingEvent$0(DedicatedServer.java:82) [ld.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71240_o(DedicatedServer.java) [ld.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:535) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at io.github.hsyyid.essentialcmds.managers.config.Config.<init>(Config.java:55) ~[Config.class:?]
        at io.github.hsyyid.essentialcmds.managers.config.Config.<clinit>(Config.java:43) ~[Config.class:?]
        ... 12 more
[14:44:45] [Server Shutdown Thread/INFO]: Stopping server

```

Thanks

**Comment by pathways029** [comment]
I'm getting this when trying to load essentials on the latest spongeforge. Is there something I need to do to install or is this a bug?

08:48:50] [Server thread/INFO]  [io.github.hsyyid.essentialcmds]: EssentialCmds loading...
[08:48:50] [Server thread/INFO] [STDERR]: [org.sqlite.SQLiteJDBCLoader:loadNativeLibrary:230]: java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.8.11.2-62dc8943-9bfe-47e1-8dbe-88c1a31afe66-libsqlitejdbc.so: /tmp/sqlite-3.8.11.2-62dc8943-9bfe-47e1-8dbe-88c1a31afe66-libsqlitejdbc.so: failed to map segment from shared object: Operation not permitted
[08:48:50] [Server thread/ERROR]  [Sponge]: Could not pass FMLInitializationEvent to Plugin{id=io.github.hsyyid.essentialcmds, name=EssentialCmds, version=@project.informativeVersion@, description=This plugin features many commands and useful features for server admins., source=~mods/EssentialCmds-1.10.2-8.1.14-universal.jar}
