### ISSUE TITLE
IllegalArgumentException: Provided object is not a plugin instance

### ISSUE THREAD

**Issue by viveleroi** [hsyyid/EssentialCmds#34]
During a `/tpahere` command, the following appeared in the console. Version 6.7

```
java.lang.IllegalArgumentException: Provided object is not a plugin instance
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[minecraft_server.1.8.jar:?]
        at org.spongepowered.common.scheduler.SpongeScheduler.checkPluginInstance(SpongeScheduler.java:154) ~[SpongeScheduler.class:1.8-1577-3.1.0-BETA-1025]
        at org.spongepowered.common.scheduler.SpongeTaskBuilder.submit(SpongeTaskBuilder.java:104) ~[SpongeTaskBuilder.class:1.8-1577-3.1.0-BETA-1025]
        at io.github.hsyyid.essentialcmds.listeners.TPAListener.tpaHereEventHandler(TPAListener.java:108) ~[TPAListener.class:6.7]
        at org.spongepowered.common.event.listener.TPAHereEventListener_TPAListener_tpaHereEventHandler34.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8-1577-3.1.0-BETA-1025]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:233) [SpongeModEventManager.class:1.8-1577-3.1.0-BETA-1025]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:277) [SpongeModEventManager.class:1.8-1577-3.1.0-BETA-1025]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:245) [SpongeModEventManager.class:1.8-1577-3.1.0-BETA-1025]
        at io.github.hsyyid.essentialcmds.cmdexecutors.TPAHereExecutor.execute(TPAHereExecutor.java:59) [TPAHereExecutor.class:6.7]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:332) [CommandSpec.class:1.8-1577-3.1.0-BETA-1025]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) [SimpleDispatcher.class:1.8-1577-3.1.0-BETA-1025]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:252) [SpongeCommandManager.class:1.8-1577-3.1.0-BETA-1025]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83) [cl.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:812) [rj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:791) [rj.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_180757_a(SourceFile:37) [lu.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [lu.class:?]
        at net.minecraft.network.PacketThreadUtil$1.onProcessPacket(SourceFile:110) [ih.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_65]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_65]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```

**Comment by Darktilldawn** [comment]
You need to update to 6.9c
