### ISSUE TITLE
Prevent invalid coordinates when saving home

### ISSUE THREAD

**Issue by viveleroi** [hsyyid/EssentialCmds#39]
A player of ours somehow made a home that proved impossible to return to:

```
Error occurred while executing command 'home Endfarm' for source EntityPlayerMP['StuntMan9630'/962, l='world', x=118.83, y=66.00, z=787.16]: Position is out of bounds: expected in range (-30000000, 0, -30000000) to (29999999, 255, 29999999) but got (-27, -1, 287)
org.spongepowered.api.util.PositionOutOfBoundsException: Position is out of bounds: expected in range (-30000000, 0, -30000000) to (29999999, 255, 29999999) but got (-27, -1, 287)
        at net.minecraft.world.World.checkBlockBounds(World.java:2052) ~[adm.class:?]
        at net.minecraft.world.World.getBlockType(World.java:1596) ~[adm.class:?]
        at org.spongepowered.api.world.extent.BlockVolume.getBlockType(BlockVolume.java:123) ~[BlockVolume.class:1.8.9-1694-3.1.0-BETA-1060]
        at org.spongepowered.common.world.SpongeTeleportHelper.isBlockSafe(SpongeTeleportHelper.java:161) ~[SpongeTeleportHelper.class:1.8.9-1694-3.1.0-BETA-1060]
        at org.spongepowered.common.world.SpongeTeleportHelper.isSafeLocation(SpongeTeleportHelper.java:156) ~[SpongeTeleportHelper.class:1.8.9-1694-3.1.0-BETA-1060]
        at org.spongepowered.common.world.SpongeTeleportHelper.checkAroundLocation(SpongeTeleportHelper.java:84) ~[SpongeTeleportHelper.class:1.8.9-1694-3.1.0-BETA-1060]
        at org.spongepowered.common.world.SpongeTeleportHelper.checkAboveAndBelowLocation(SpongeTeleportHelper.java:74) ~[SpongeTeleportHelper.class:1.8.9-1694-3.1.0-BETA-1060]
        at org.spongepowered.common.world.SpongeTeleportHelper.getSafeLocation(SpongeTeleportHelper.java:48) ~[SpongeTeleportHelper.class:1.8.9-1694-3.1.0-BETA-1060]
        at org.spongepowered.common.world.SpongeTeleportHelper.getSafeLocation(SpongeTeleportHelper.java:42) ~[SpongeTeleportHelper.class:1.8.9-1694-3.1.0-BETA-1060]
        at net.minecraft.entity.Entity.setLocation(Entity.java:324) ~[pk.class:?]
        at net.minecraft.entity.Entity.setLocationSafely(Entity.java:291) ~[pk.class:?]
        at net.minecraft.entity.Entity.transferToWorld(Entity.java:494) ~[pk.class:?]
        at io.github.hsyyid.essentialcmds.cmdexecutors.HomeExecutor.execute(HomeExecutor.java:68) ~[HomeExecutor.class:6.9]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:332) ~[CommandSpec.class:1.8.9-1694-3.1.0-BETA-1060]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331) ~[SimpleDispatcher.class:1.8.9-1694-3.1.0-BETA-1060]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:252) [SpongeCommandManager.class:1.8.9-1694-3.1.0-BETA-1060]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83) [bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:809) [lm.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:788) [lm.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ie.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ie.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:106) [PacketUtil.class:1.8.9-1694-3.1.0-BETA-1060]
        at net.minecraft.network.PacketThreadUtil$1.onProcessPacket(SourceFile:51) [fh$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_65]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_65]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```

**Comment by hsyyid** [comment]
I think this is because Sponge tries to safely teleport you to the location, so you do not die.

EDIT: Nope, that is not the case. What is happening is I am assuming this home was created in the end, and the player set the home _in the void_ if you do this, it'll be impossible to return to, I will fix this so it does not throw an error if it is out of bounds.
