### ISSUE TITLE
Error on MySQL Enable

### ISSUE THREAD

**Issue by ThornsOfire** [hsyyid/EssentialCmds#41]
SpongeForge 1094
Forge 1694

```
[22:41:42] [Server thread/INFO] [EssentialCmds]: EssentialCmds loading...
[22:41:42] [Server thread/INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool
-0 - is starting.
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]: java.sql.SQLSyntaxErrorException: La colonne 'UUID' de type
BLOB est utilisée dans une définition d'index sans longueur d'index
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.mariadb.jdbc.internal.util.ExceptionMapper.get(Ex
ceptionMapper.java:125)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.mariadb.jdbc.internal.util.ExceptionMapper.throwE
xception(ExceptionMapper.java:69)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(
MariaDbStatement.java:261)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStat
ement.java:290)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStat
ement.java:344)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxySt
atement.java:95)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.zaxxer.hikari.pool.HikariProxyStatement.execute(H
ikariProxyStatement.java)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at io.github.hsyyid.essentialcmds.utils.Utils.execute(Ut
ils.java:396)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at io.github.hsyyid.essentialcmds.utils.Utils.readMutes(
Utils.java:423)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at io.github.hsyyid.essentialcmds.EssentialCmds.onServer
Init(EssentialCmds.java:119)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.spongepowered.common.event.listener.GameInitializ
ationEventListener_EssentialCmds_onServerInit16.handle(Unknown Source)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.spongepowered.common.event.RegisteredListener.han
dle(RegisteredListener.java:86)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.spongepowered.mod.event.SpongeModEventManager.pos
t(SpongeModEventManager.java:233)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.spongepowered.mod.event.SpongeModEventManager.pos
t(SpongeModEventManager.java:277)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMo
d.java:185)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at java.lang.reflect.Method.invoke(Unknown Source)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventSubscriber.handleEven
t(EventSubscriber.java:74)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.SynchronizedEventSubscribe
r.handleEvent(SynchronizedEventSubscriber.java:47)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventBus.dispatch(EventBus
.java:322)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventBus.dispatchQueuedEve
nts(EventBus.java:304)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventBus.post(EventBus.jav
a:275)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraftforge.fml.common.LoadController.sendEven
tToModContainer(LoadController.java:211)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraftforge.fml.common.LoadController.propogat
eStateMessage(LoadController.java:189)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at java.lang.reflect.Method.invoke(Unknown Source)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventSubscriber.handleEven
t(EventSubscriber.java:74)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.SynchronizedEventSubscribe
r.handleEvent(SynchronizedEventSubscriber.java:47)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventBus.dispatch(EventBus
.java:322)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventBus.dispatchQueuedEve
nts(EventBus.java:304)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventBus.post(EventBus.jav
a:275)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraftforge.fml.common.LoadController.onPost(L
oadController.java:53)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraftforge.fml.common.LoadController.distribu
teStateMessage(LoadController.java:118)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraftforge.fml.common.Loader.initializeMods(L
oader.java:735)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraftforge.fml.server.FMLServerHandler.finish
ServerLoading(FMLServerHandler.java:97)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraftforge.fml.common.FMLCommonHandler.onServ
erStarted(FMLCommonHandler.java:324)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraft.server.dedicated.DedicatedServer.func_7
1197_b(DedicatedServer.java:205)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:441)
[22:41:42] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at java.lang.Thread.run(Unknown Source)
[22:41:42] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-
1]: Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: La colonne 'UU
ID' de type BLOB est utilisée dans une définition d'index sans longueur d'index
[22:41:42] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-
1]:     at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(Ab
stractQueryProtocol.java:475)
[22:41:42] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-
1]:     at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.result(Abstr
actQueryProtocol.java:396)
[22:41:42] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-
1]:     at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery
(AbstractQueryProtocol.java:378)
[22:41:42] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-
1]:     at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery
(AbstractQueryProtocol.java:334)
[22:41:42] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-
1]:     at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:280)
[22:41:42] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-
1]:     ... 39 more
[22:41:43] [Server thread/INFO] [EssentialCmds]: -----------------------------
[22:41:43] [Server thread/INFO] [EssentialCmds]: EssentialCmds was made by Hassa
nS6000!
[22:41:43] [Server thread/INFO] [EssentialCmds]: Please post all errors on the S
ponge Thread or on GitHub!
[22:41:43] [Server thread/INFO] [EssentialCmds]: Have fun, and enjoy! :D
[22:41:43] [Server thread/INFO] [EssentialCmds]: -----------------------------
[22:41:43] [Server thread/INFO] [EssentialCmds]: EssentialCmds loaded!
```

**Comment by hsyyid** [comment]
What version of Sponge is this on?
What version of Minecraft and/or Forge?
What version of EssentialCmds?

**Comment by ThornsOfire** [comment]
Java 1.8.0_71
64 bit
mcp 9.18
FML 8.0.99.99
forge 1.8.9-11.15.0.1694
sponge 1.8.9-1694-3.1.0-BETA 1084
AdminShop 1.3c
AntiSwear 1.1.3
ArmorHUD 1.0
Blood Money 0.2.8
EssentialCmds 7.1-ec3ebe2
FoxCore-v0.6.2-70
Kits 1.3c
landiscovery 1.0.1
PermissionsEx 2.0-SNAPSHOT
PvPLogger 1.1
TotalEconomy 1.3.1
Vanish 4.0.0
worldedit-forge-mc 1.8.9-6.1.1

**Comment by ThornsOfire** [comment]
Same error running Minecraft Forge: 11.15.1.1722

**Comment by hsyyid** [comment]
Please try updating to SpongeForge 1103,

Also please send logs in English if possible :smile:

**Comment by ThornsOfire** [comment]
Will do, we have also added a few plugins and updated a number as well, Would you like an updated versions log?

**Comment by ThornsOfire** [comment]
[20:29:22] [Server thread/INFO] [EssentialCmds]: EssentialCmds loading...
[20:29:22] [Server thread/INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool
-0 - is starting.
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]: java.sql.SQLSyntaxErrorException: La colonne 'UUID' de type
BLOB est utilisée dans une définition d'index sans longueur d'index
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.mariadb.jdbc.internal.util.ExceptionMapper.get(Ex
ceptionMapper.java:125)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.mariadb.jdbc.internal.util.ExceptionMapper.throwE
xception(ExceptionMapper.java:69)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(
MariaDbStatement.java:261)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStat
ement.java:290)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStat
ement.java:344)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxySt
atement.java:95)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.zaxxer.hikari.pool.HikariProxyStatement.execute(H
ikariProxyStatement.java)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at io.github.hsyyid.essentialcmds.utils.Utils.execute(Ut
ils.java:396)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at io.github.hsyyid.essentialcmds.utils.Utils.readMutes(
Utils.java:423)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at io.github.hsyyid.essentialcmds.EssentialCmds.onServer
Init(EssentialCmds.java:119)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.spongepowered.common.event.listener.GameInitializ
ationEventListener_EssentialCmds_onServerInit16.handle(Unknown Source)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.spongepowered.common.event.RegisteredListener.han
dle(RegisteredListener.java:86)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.spongepowered.mod.event.SpongeModEventManager.pos
t(SpongeModEventManager.java:236)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.spongepowered.mod.event.SpongeModEventManager.pos
t(SpongeModEventManager.java:280)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMo
d.java:185)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at java.lang.reflect.Method.invoke(Unknown Source)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventSubscriber.handleEven
t(EventSubscriber.java:74)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.SynchronizedEventSubscribe
r.handleEvent(SynchronizedEventSubscriber.java:47)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventBus.dispatch(EventBus
.java:322)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventBus.dispatchQueuedEve
nts(EventBus.java:304)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventBus.post(EventBus.jav
a:275)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraftforge.fml.common.LoadController.sendEven
tToModContainer(LoadController.java:211)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraftforge.fml.common.LoadController.propogat
eStateMessage(LoadController.java:189)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at java.lang.reflect.Method.invoke(Unknown Source)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventSubscriber.handleEven
t(EventSubscriber.java:74)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.SynchronizedEventSubscribe
r.handleEvent(SynchronizedEventSubscriber.java:47)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventBus.dispatch(EventBus
.java:322)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventBus.dispatchQueuedEve
nts(EventBus.java:304)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at com.google.common.eventbus.EventBus.post(EventBus.jav
a:275)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraftforge.fml.common.LoadController.onPost(L
oadController.java:53)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraftforge.fml.common.LoadController.distribu
teStateMessage(LoadController.java:118)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraftforge.fml.common.Loader.initializeMods(L
oader.java:737)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraftforge.fml.server.FMLServerHandler.finish
ServerLoading(FMLServerHandler.java:97)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraftforge.fml.common.FMLCommonHandler.onServ
erStarted(FMLCommonHandler.java:325)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraft.server.dedicated.DedicatedServer.func_7
1197_b(DedicatedServer.java:205)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:441)
[20:29:22] [Server thread/INFO] [STDERR]: [io.github.hsyyid.essentialcmds.utils.
Utils:execute:403]:     at java.lang.Thread.run(Unknown Source)
[20:29:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-
1]: Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: La colonne 'UU
ID' de type BLOB est utilisée dans une définition d'index sans longueur d'index
[20:29:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-
1]:     at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(Ab
stractQueryProtocol.java:475)
[20:29:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-
1]:     at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.result(Abstr
actQueryProtocol.java:396)
[20:29:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-
1]:     at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery
(AbstractQueryProtocol.java:378)
[20:29:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-
1]:     at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery
(AbstractQueryProtocol.java:334)
[20:29:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-
1]:     at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:280)
[20:29:22] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-
1]:     ... 39 more
[20:29:23] [Server thread/INFO] [EssentialCmds]: -----------------------------
[20:29:23] [Server thread/INFO] [EssentialCmds]: EssentialCmds was made by Hassa
nS6000!
[20:29:23] [Server thread/INFO] [EssentialCmds]: Please post all errors on the S
ponge Thread or on GitHub!
[20:29:23] [Server thread/INFO] [EssentialCmds]: Have fun, and enjoy! :D
[20:29:23] [Server thread/INFO] [EssentialCmds]: -----------------------------
[20:29:23] [Server thread/INFO] [EssentialCmds]: EssentialCmds loaded!

Posting them anyways <3

Versions

Java 1.8.0_71
64 bit
mcp 9.18
FML 8.0.99.99
minecraft_server.1.8.9
Forge: 11.15.1.1722
spongeforge-1.8.9-1722-3.1.0-BETA-1103
AdminShop-1.3c
AntiSwear 1.1.3
ArmorHUD v1.0
Blood Money 0.2.8
Ember-1.0-SNAPSHOT
EssentialCmds-7.1
FoxCore-v0.6.2-70-SNAPSHOT
Kits-1.3c
landiscovery-1.0.1
LootCrate-1.1-Beta
PermissionsEx-Sponge-2.0
Polis-1.8b
PvPLogger-1.1
ServerListPlusSponge-3.4.1-SNAPSHOT
TotalEconomy-v1.3.1
UltimateGames-0.3
vanish4.0.0
worldedit-forge-mc1.8.9-6.1.1
XtraPunish-1.1

**Comment by ThornsOfire** [comment]
I can see that there is some french in there, I am using english on my computer/console/server/everything lol not sure whats going on there

**Comment by hsyyid** [comment]
Okay, I'll test it out, not sure what the issue is. Also please use [PasteBin](http://pastebin.com) for future logs.

**Comment by ThornsOfire** [comment]
Yeah sorry not sure why I didn't... lol

Let me know if you need me to test anything, I check github often.

**Comment by hsyyid** [comment]
@ThornsOfire Has this been resolved?

**Comment by cartman-2000** [comment]
I get this error on the creation of the mutes table. The length of the UUID varchar doesn't need to be that long it only needs to be ~36 characters long.

OS: Windows 10
Mysql: 5.5.40
Java: 1.8.0_91 64 bit
SpongeForge version: 1.10.2-2002-5.0.0-BETA-1525

```
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]: java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
Query is : CREATE TABLE IF NOT EXISTS MUTES (UUID VARCHAR(256) PRIMARY KEY NOT NULL)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:242)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:270)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:283)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at io.github.hsyyid.essentialcmds.utils.Utils.execute(Utils.java:598)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at io.github.hsyyid.essentialcmds.utils.Utils.addMute(Utils.java:136)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at io.github.hsyyid.essentialcmds.cmdexecutors.MuteExecutor.executeAsync(MuteExecutor.java:66)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at io.github.hsyyid.essentialcmds.internal.AsyncCommandExecutorBase.lambda$execute$0(AsyncCommandExecutorBase.java:54)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at java.util.concurrent.FutureTask.run(Unknown Source)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [io.github.hsyyid.essentialcmds.utils.Utils:execute:605]:    at java.lang.Thread.run(Unknown Source)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Specified key was too long; max key length is 767 bytes
Query is : CREATE TABLE IF NOT EXISTS MUTES (UUID VARCHAR(256) PRIMARY KEY NOT NULL)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [java.lang.Throwable:printStackTrace:-1]:    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:938)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [java.lang.Throwable:printStackTrace:-1]:    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:604)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [java.lang.Throwable:printStackTrace:-1]:    at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:261)
[12:56:00] [pool-2-thread-3/INFO] [STDERR/sponge]: [java.lang.Throwable:printStackTrace:-1]:    ... 14 more
```

Also for windows compatibility, you should have the table names and database name in lowercase only, while it does still work when you use uppercase, you can't do a direct rename(by changing case only.), and you get a warning printed out in the mysql logs on every start about uppercase letters being used in the names.

**Comment by kherock** [comment]
I'm getting the same error as @cartman-2000 on Windows with MariaDB, so I'm unable to use MySQL backend. Can this be fixed soon?
