### ISSUE TITLE
[1.9] Issue ClientConnectionEvent

### ISSUE THREAD

**Issue by jmiahman** [hsyyid/EssentialCmds#93]
Running EssentialCmds on the unsupported only 90% done 1.9 Branch of Sponge I get..

```
[16:18:34] [Netty Epoll Server IO #1/DEBUG] [mixin]: Mixing util.MixinPacketThreadUtil from mixins.common.core.json into net.minecraft.network.PacketThreadUtil$1
[16:18:34] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=io.github.hsyyid.essentialcmds, name=EssentialCmds, version=8.1.0-4760d4c, description=This plugin features many commands and useful features for server admins., source=mods/EssentialCmds-8.1.0.jar}
java.lang.NoSuchMethodError: org.spongepowered.api.entity.living.player.Player.setLocationSafely(Lorg/spongepowered/api/world/Location;)Z
    at io.github.hsyyid.essentialcmds.listeners.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:87) ~[PlayerJoinListener.class:8.1.0]
    at org.spongepowered.common.event.listener.JoinListener_PlayerJoinListener_onPlayerJoin5.handle(Unknown Source) ~[?:?]
    at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.9-6.0.0-BETA-0]
    at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:258) [SpongeEventManager.class:1.9-6.0.0-BETA-0]
    at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:269) [SpongeEventManager.class:1.9-6.0.0-BETA-0]
    at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:138) [SpongeImpl.class:1.9-6.0.0-BETA-0]
    at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(SourceFile:374) [mm.class:?]
    at net.minecraft.server.management.PlayerList.func_72355_a(SourceFile:144) [mm.class:?]
    at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(SourceFile:116) [md.class:?]
    at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(SourceFile:62) [md.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(SourceFile:232) [ek.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(SourceFile:187) [ma.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:193) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:339) [la.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:553) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(SourceFile:457) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

Full log can be found here..

http://theloveoflinux.com/logs/test/latest.log

I have sent you information about a test server with 1.9 if there's anything else you need, or need me to test let me know. Thanks

**Comment by liach** [comment]
The api breaks. Do not use plugin that supports api 4 on api 6.

**Comment by jmiahman** [comment]
I know the API breaks, I am reporting it so he knows what's broke. The plugin for the most part works quite well on api 6. He mentioned he might make a branch for 1.9 so I thought I would report what I am seeing now so if he does he has something to work with.

**Comment by jmiahman** [comment]
This issue seems to be fixed on a new world with the latest Bleeding builds of Sponge from git.
